# Generated by Django 4.2.6 on 2023-12-11 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("chains", "0013_chainedge_source_key_chainedge_target_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("task_log", "0012_task_root_tasklogmessage_root"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunnableExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(null=True)),
                ("completed", models.BooleanField(default=False)),
                ("inputs", models.JSONField(default=dict, null=True)),
                ("outputs", models.JSONField(default=dict, null=True)),
                ("message", models.TextField(null=True)),
                (
                    "group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chains.chainnode",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="task_log.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["task", "-started_at"],
            },
        ),
    ]
