# Generated by Django 4.2.7 on 2024-02-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runnable_log", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="runnableexecution",
            name="parent_id",
            field=models.UUIDField(null=True),
        ),
    ]
