# Generated by Django 4.2.6 on 2023-10-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secrets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecretValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=73)),
                ("data", models.JSONField()),
            ],
        ),
    ]
