# Generated by Django 4.2 on 2023-05-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0003_remove_agent_commands_remove_agent_system_prompt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="alias",
            field=models.CharField(default="planner", max_length=63),
            preserve_default=False,
        ),
    ]
