# Generated by Django 4.2.2 on 2023-07-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0004_agent_alias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="config",
            field=models.JSONField(default=dict),
        ),
    ]
