# Generated by Django 4.2.2 on 2023-09-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0006_remove_agent_agent_class_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="is_test",
            field=models.BooleanField(default=False),
        ),
    ]
