# Generated by Django 4.2 on 2023-04-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_log", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="autonomous",
            field=models.BooleanField(default=True),
        ),
    ]
