# Generated by Django 4.2 on 2023-05-06 23:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_log", "0003_plan_alter_tasklogmessage_task_plansteps_artifact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="goals",
        ),
    ]
