# Generated by Django 4.2 on 2023-05-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_log", "0005_rename_artifact_storage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plansteps",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="plansteps",
            name="order",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
