# Generated by Django 4.2 on 2023-05-08 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0001_initial"),
        ("agents", "0004_agent_alias"),
        ("task_log", "0006_alter_plansteps_options_plansteps_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="chain",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="chains.chain",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="agent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="agents.agent",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="task_log.task",
            ),
        ),
    ]
