# Generated by Django 4.2.1 on 2023-05-22 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("task_log", "0007_task_chain_alter_task_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="task_log.task",
            ),
        ),
    ]
