# Generated by Django 4.2.6 on 2023-12-08 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("task_log", "0011_artifact_group_artifact_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="root",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="descendants",
                to="task_log.task",
            ),
        ),
    ]
