# Generated by Django 4.2.1 on 2023-06-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0003_add_chain_node_chain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chainedge",
            name="root",
        ),
        migrations.RemoveField(
            model_name="chainnode",
            name="root",
        ),
        migrations.AddField(
            model_name="chainnode",
            name="root",
            field=models.BooleanField(default=False),
        ),
    ]
