# Generated by Django 4.2.2 on 2023-06-20 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0005_refine_node_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chain",
            name="root",
        ),
        migrations.RemoveField(
            model_name="chainnode",
            name="parent",
        ),
        migrations.AddField(
            model_name="chainedge",
            name="relation",
            field=models.CharField(
                choices=[("PROP", "prop"), ("LINK", "link")],
                default="LINK",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chainnode",
            name="node_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chains.nodetype",
            ),
        ),
    ]
