# Generated by Django 4.2.2 on 2023-07-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0006_chain_editor_support_part_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chainnode",
            name="config",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
