# Generated by Django 4.2.2 on 2023-09-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0009_chain_is_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodetype",
            name="class_path",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
