# Generated by Django 4.2.5 on 2023-10-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0010_alter_nodetype_class_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodetype",
            name="field_groups",
            field=models.JSONField(null=True),
        ),
    ]
