# Generated by Django 4.2.6 on 2023-11-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0012_chain_group_chain_user_nodetype_group_nodetype_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodetype",
            name="context",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
