# Generated by Django 4.2.6 on 2023-11-04 16:04

from django.db import migrations, models


def convert_to_types(apps, schema_editor):
    Chain = apps.get_model("chains", "Chain")
    for chain in Chain.objects.all():
        chain.type = "agent" if chain.is_agent else "chain"
        chain.save()


def convert_to_is_agent(apps, schema_editor):
    Chain = apps.get_model("chains", "Chain")
    for chain in Chain.objects.all():
        chain.is_agent = chain.type == "agent"
        chain.save()


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0013_nodetype_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="type",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.RunPython(
            code=convert_to_types,
            reverse_code=convert_to_is_agent,
        ),
    ]
