# Generated by Django 4.2.7 on 2024-02-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0015_langchain_0_1_0_deprecations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chainedge",
            name="relation",
            field=models.CharField(
                choices=[("PROP", "prop"), ("LINK", "link")],
                default="LINK",
                max_length=5,
                null=True,
            ),
        ),
    ]
