# Generated by Django 4.2.6 on 2024-01-15 17:29

from django.db import migrations

from ix.utils.django.migrations import UpdateComponentClassPath


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0016_alter_chainedge_relation"),
    ]

    operations = [
        UpdateComponentClassPath(
            [
                (
                    "langchain.prompts.chat.ChatPromptTemplate",
                    "ix.runnable.prompt.ChatPrompt",
                ),
            ]
        )
    ]
