# Generated by Django 4.2.1 on 2023-06-04 03:16

from django.db import migrations, models
import ix.pg_vector.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS vector;"),
        migrations.CreateModel(
            name="Embedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("text", models.TextField()),
                (
                    "embedding",
                    ix.pg_vector.fields.VectorField(
                        base_field=models.FloatField(), null=True, size=3
                    ),
                ),
                (
                    "null_embedding",
                    ix.pg_vector.fields.VectorField(
                        base_field=models.FloatField(), null=True, size=3
                    ),
                ),
            ],
            options={
                "db_table": "embeddings",
            },
        ),
    ]
