# Generated by Django 4.2.2 on 2023-09-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="is_test",
            field=models.BooleanField(default=False),
        ),
    ]
